### ISSUE TITLE
How simply add new space? (without creating many points)

### ISSUE THREAD

**Issue by liliasapurina** [SergeyBudnik/SmartConfig#42]
Now it is hard to support a lot of different spaces, because we need to create too many points.
Will be great to find solution how cheaply add new space.

**Comment by SergeyBudnik** [comment]
@liliasapurina 

have in mind the following syntax:

dimensions {
  env: [sit, uat]
  zone: [uk, us]
}

points {
  {env: sit, zone: uk}
  {env: uat, zone: *}
}

have to check about '*', probably it is a reserved keyword and will be replaced with 'all'

**Comment by liliasapurina** [comment]
@SergeyBudnik 
Unfortunately it is not working for me:
``
Failed to execute goal com.github.sergeybudnik:smart.config:3.4.1:jenesis4java (default) on project aap-e2e-utils: ...\src\main\resources\smart-config-data\smart-config-dimensions.conf: 9: Ex
pecting close brace } or a comma, got '*' (Reserved character '*' is not allowed outside quotes) (if you intended '*' (Reserved character '*' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes) ->
``

**Comment by SergeyBudnik** [comment]
This feature belongs to 3.5.0 release. Just created a pull request for it.

To understand how it will work, please check tests:
https://github.com/SergeyBudnik/SmartConfig/pull/45/files

**Comment by liliasapurina** [comment]
Thanks!
